default[:omnibus_ohai_solo][:repo] = "https://github.com/ryandub/omnibus-ohai-solo.git"
default[:omnibus_ohai_solo][:ref]  = "master"
default[:omnibus_ohai_solo][:release_environment] = "dev"
default[:omnibus_ohai_solo][:append_timestamp] = "true"
default[:ohai_plugins][:repo] = "https://github.com/rackerlabs/ohai-plugins.git"
default[:ohai_plugins][:ref]  = "master"
