#!/bin/bash
#
# Perform necessary ohai-solo setup steps
# after package is installed.
#

PROGNAME=$(basename $0)

function error_exit
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

rm /usr/bin/ohai-solo
ln -s /opt/ohai-solo/bin/ohai-solo /usr/bin/ohai-solo
echo "Thank you for installing ohai-solo!"

exit 0
